### ISSUE TITLE
Cannot verify ETH address with MetaMask

### ISSUE THREAD

**Issue by Phoenix616** [bountysource/core#1469]
Pressing the "Add through Metamask" button shows the following errors in the debug console:

Using:
- Chromium 84.0.4128.0
- MetaMask 7.7.9 

```
Error verifying account Error: [ethjs-query] while formatting inputs '[[{"type":"string","name":"Message","value":"By signing this transaction, I prove my ownership of account undefined"}],null]' for method 'signTypedData' error: Error: [ethjs-format] hex string 'undefined' must be an alphanumeric 42 utf8 byte hex (chars: a-fA-F) string, is 0 bytes
(anonymous) @ angular.min.jsm?_=b3c648fe3ec22e9f96bb9807:89
```
```
Error when validating ETH addrs Error: Error verifying account Error: [ethjs-query] while formatting inputs '[[{"type":"string","name":"Message","value":"By signing this transaction, I prove my ownership of account undefined"}],null]' for method 'signTypedData' error: Error: [ethjs-format] hex string 'undefined' must be an alphanumeric 42 utf8 byte hex (chars: a-fA-F) string, is 0 bytes
(anonymous) @ angular.min.jsm?_=b3c648fe3ec22e9f96bb9807:89
```

**Comment by johanlives** [comment]
> Pressing the "Add through Metamask" button shows the following errors in the debug console:
> 
> Using:
> 
> * Chromium 84.0.4128.0
> * MetaMask 7.7.9
> 
> ```
> Error verifying account Error: [ethjs-query] while formatting inputs '[[{"type":"string","name":"Message","value":"By signing this transaction, I prove my ownership of account undefined"}],null]' for method 'signTypedData' error: Error: [ethjs-format] hex string 'undefined' must be an alphanumeric 42 utf8 byte hex (chars: a-fA-F) string, is 0 bytes
> (anonymous) @ angular.min.jsm?_=b3c648fe3ec22e9f96bb9807:89
> ```
> 
> ```
> Error when validating ETH addrs Error: Error verifying account Error: [ethjs-query] while formatting inputs '[[{"type":"string","name":"Message","value":"By signing this transaction, I prove my ownership of account undefined"}],null]' for method 'signTypedData' error: Error: [ethjs-format] hex string 'undefined' must be an alphanumeric 42 utf8 byte hex (chars: a-fA-F) string, is 0 bytes
> (anonymous) @ angular.min.jsm?_=b3c648fe3ec22e9f96bb9807:89
> ```

Hi @Phoenix616 
We are working several Bountysource maintenance & improvement issues.
Crypto is not a popular payment method presently and it fix is currently lower than other critical services and functions.
We will update when there is an ETA

**Comment by Phoenix616** [comment]
Would be nice if claims would work without Metamask verification of addresses for the meantime.

**Comment by Phoenix616** [comment]
This should be fixed asap now that claims will expire after two years. Otherwise people will not be able to claim their ETH bounties...

**Comment by istnv** [comment]
This is still does not work.
Linux/Ubuntu with Chrome 89.0.4389.90 or Firefox 86.0

**Comment by kaovilai** [comment]
I can't pay with crypto due to similar metamask error so the point that crypto is not popular is to be expected due to broken functionality.
